server:
  port: 8081
spring:
  datasource:
    druid:
      url: jdbc:mysql://192.168.1.101:3306/mybatis?useUnicode=true&characterEncoding=utf8
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: rootroot
mybatis:
  check-config-location: false
  type-aliases-package: com.mine.siis.pojo
  #MyBatis Mapper 所对应的 XML 文件位置
  mapper-locations: classptha:mapper/*.xml
  config-location: classpath:/mybatis/mybatis-config.xml

logging.level.org.springframework.boot.autoconfigure: ERROR